baseurl: /

# Site settings
title: mias ting
email: miasbetaversion@gmail.com
description: "Jeg bevæger mig bredt på paletten. Her er nogle af de ting jeg har lavet."


# Profile, brugt i hvad tidligere var about-sektion, og nu er kontakt-sektion
profilename: Mia Andersen
profilepic: mia_profil
profileposition: Lead 
profilesocial:
    - title: facebook
      url: https://www.facebook.com/miacaroline.andersen
    - title: github
      url: http://github.com/miasting


# Build settings
markdown: kramdown
permalink: pretty
